### ISSUE TITLE
Installation fails due to wrong image used by the apicurito-service deployment

### ISSUE THREAD

**Issue by JameelB** [Apicurio/apicurio-operators#22]
Apicurito installation fails due to a typo on the image referenced by the `apicurito-service` deployment which is created by the operator. Instead of referencing `registry.redhat.io/fuse7/fuse-apicurito:1.5`, it uses `registry.redhat.io/fuse7-fuse-apicurito:1.5` instead.

The following error can be seen in the deployment status:
```
containerStatuses:
    - name: apicurito
      state:
        waiting:
          reason: ImagePullBackOff
          message: 'Back-off pulling image "registry.redhat.io/fuse7-fuse-apicurito:1.5"'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'registry.redhat.io/fuse7-fuse-apicurito:1.5'
      imageID: ''
      started: false
```

Error seen in the pod events:
```
Failed to pull image "registry.redhat.io/fuse7-fuse-apicurito:1.5": rpc error: code = Unknown desc = Error reading manifest 1.5 in registry.redhat.io/fuse7-fuse-apicurito: unknown: Not Found
```

**Operator image used for this installation**: [registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.5](https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/fuse7-tech-preview/fuse-apicurito-operator)
**CR used for this installation**:
```
apiVersion: apicur.io/v1alpha1
kind: Apicurito
metadata:
  name: apicurito-service
spec:
  size: 2
```
